services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=urlshortener
      - DB_PASSWORD=password
      - DB_NAME=urlshortener_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
      - /app/tmp
      - /app/frontend/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - urlshortener

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: urlshortener_db
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../configs/database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshortener -d urlshortener_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - urlshortener

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - urlshortener

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - urlshortener

volumes:
  postgres_data:
  redis_data:

networks:
  urlshortener:
    driver: bridge